import type { NextPage } from "next";
import Link from "next/link";
import * as contentful from "contentful";
import Head from "next/head";
import Header from "../../components/common/header";
import Footer from "../../components/common/footer";
import ProductList from "../../components/common/PreviewList";

export async function getStaticProps() {
  const client = contentful.createClient({
    space: process.env.SPACE,
    accessToken: process.env.ACCESS_TOKEN,
  });

  const res = await client.getEntries({ content_type: "activities" });

  return {
    props: {
      activities: res.items,
    },
  };
}

const Activities: NextPage = ({ activities }) => {
  console.log(activities);

  return (
    <div className="container">
      <Head>
        <title>Attività</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ProductList products={activities} title="Attività" />
      <Footer />
    </div>
  );
};
export default Activities;
